### ISSUE TITLE
Fix the Estop code, Carl!

### ISSUE THREAD

**Issue by ConnorNovak** [olinrobotics/tractor#10]

**Comment by ConnorNovak** [comment]
The error occurs first, it seems, when a new estop is instantiated on line 77:

e = new Estop(&nh,ESTOP_PIN,1);

**Comment by ConnorNovak** [comment]
Potentially fixed; needs integration and testing

**Comment by cmoser96** [comment]
Integrated in commit  aeb56474f2445db628f0b490220d1aecb0e04108, needs testing
